# Generated by Django 4.2.1 on 2023-06-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceModel",
            fields=[
                (
                    "device_id",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="資産番号",
                    ),
                ),
                (
                    "manufacture",
                    models.CharField(
                        choices=[
                            ("DELL", "DELL"),
                            ("HP", "HP"),
                            ("Lenovo", "Lenovo"),
                            ("Chrome", "Chrome"),
                            ("Apple", "Apple"),
                            ("Microsoft", "Microsoft"),
                            ("NEC", "NEC"),
                            ("FUJITSU", "FUJITSU"),
                            ("Panasonic", "Panasonic"),
                            ("LG Electronics", "LG Electronics"),
                            ("VAIO", "VAIO"),
                            ("dynabook", "dynabook"),
                            ("MouseComputer", "MouseComputer"),
                            ("Dospara", "Dospara"),
                            ("パソコン工房", "パソコン工房"),
                            ("ASUS", "ASUS"),
                            ("ELECOM", "ELECOM"),
                            ("BUFFALO", "BUFFALO"),
                            ("SANWA SUPPLY", "SANWA SUPPLY"),
                            ("Digio", "Digio"),
                            ("Logicool", "Logicool"),
                            ("Razer", "Razer"),
                            ("Kensington", "Kensington"),
                            ("その他", "その他"),
                        ],
                        max_length=20,
                        verbose_name="メーカー",
                    ),
                ),
                ("model_name", models.CharField(max_length=50, verbose_name="機器名")),
                (
                    "device_type",
                    models.CharField(
                        choices=[("PC", "PC"), ("マウス", "マウス"), ("その他", "その他")],
                        max_length=30,
                        verbose_name="機器タイプ",
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Windows", "Windows"),
                            ("Mac OS", "Mac OS"),
                            ("Linux", "Linux"),
                            ("Unix", "Unix"),
                            ("Chrome OS", "Chrome OS"),
                            ("その他", "その他"),
                        ],
                        default=None,
                        max_length=10,
                        null=True,
                        verbose_name="OS",
                    ),
                ),
                (
                    "memory",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("2", "2GB"),
                            ("4", "4GB"),
                            ("8", "8GB"),
                            ("16", "16GB"),
                            ("32", "32GB"),
                            ("64", "64GB"),
                            ("その他", "その他"),
                        ],
                        default=None,
                        max_length=10,
                        null=True,
                        verbose_name="メモリ",
                    ),
                ),
                (
                    "storage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("128", "128GB"),
                            ("256", "256GB"),
                            ("512", "512GB"),
                            ("1", "1TB"),
                            ("2", "2TB"),
                            ("その他", "その他"),
                        ],
                        default=None,
                        max_length=10,
                        null=True,
                        verbose_name="ストレージ",
                    ),
                ),
                (
                    "gpu",
                    models.CharField(
                        blank=True,
                        choices=[("あり", "あり"), ("なし", "なし")],
                        default=None,
                        max_length=3,
                        null=True,
                        verbose_name="GPU",
                    ),
                ),
                (
                    "is_faulty",
                    models.BooleanField(default=False, null=True, verbose_name="故障"),
                ),
                ("inventry_date", models.DateField(verbose_name="棚卸し日")),
                (
                    "registration_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日"),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                (
                    "commencement_date",
                    models.DateField(blank=True, null=True, verbose_name="リース開始日"),
                ),
                (
                    "expiration_date",
                    models.DateField(blank=True, null=True, verbose_name="リース終了日"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=200, null=True, verbose_name="備考"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="削除フラグ"),
                ),
            ],
        ),
    ]
