# Generated by Django 4.2.1 on 2023-06-30 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsersModel",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(regex="^[0-9]+$")
                        ],
                        verbose_name="社員番号",
                    ),
                ),
                ("name", models.CharField(max_length=15, verbose_name="氏名")),
                ("kana_name", models.CharField(max_length=15, verbose_name="シメイ")),
                ("birthday", models.DateField(verbose_name="生年月日")),
                (
                    "gender",
                    models.CharField(
                        choices=[("男性", "男性"), ("女性", "女性"), ("その他", "その他")],
                        max_length=5,
                        verbose_name="性別",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(regex="^[0-9]+$")
                        ],
                        verbose_name="電話番号",
                    ),
                ),
                ("mail", models.EmailField(max_length=40, verbose_name="メールアドレス")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("一般", "一般"),
                            ("係長", "係長"),
                            ("課長", "課長"),
                            ("部長", "部長"),
                            ("取締役", "取締役"),
                            ("社長", "社長"),
                            ("その他", "その他"),
                        ],
                        max_length=20,
                        verbose_name="役職",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("開発1課", "開発1課"),
                            ("開発2課", "開発2課"),
                            ("営業1課", "営業1課"),
                            ("営業2課", "営業2課"),
                            ("情報システム部", "情報システム部"),
                            ("その他", "その他"),
                        ],
                        max_length=10,
                        verbose_name="部署",
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        choices=[("管理者", "管理者"), ("利用者", "利用者")],
                        max_length=10,
                        verbose_name="権限",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日"),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=200, null=True, verbose_name="備考"
                    ),
                ),
                (
                    "retirement_date",
                    models.DateTimeField(null=True, verbose_name="退職日"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="削除フラグ"),
                ),
            ],
        ),
    ]
